### ISSUE TITLE
User can see the next letter they need to type.

### ISSUE THREAD

**Issue by franzsalvador** [FranzCSUF/typing-tutor#2]
# 💰 Motivation
The user needs to know how far along they are in the phrase.

# ⚙️ Implementation
- [x] Create an `Object` to represent the application state, and make the characters a property.
- [x] Add a property to the application state to track the index of the `currentCharacter`.
- [x] Define a CSS class to highlight the `current-character`.
- [x] Enhance function that renders a character to conditionally add a special `current-character` class.

![see-next-letter](https://user-images.githubusercontent.com/39274811/40800075-2f1da51e-64c4-11e8-855e-6a7af927f38e.png)

**Comment by FranzCSUF** [comment]
# 💰 Motivation
The user needs to know how far along they are in the phrase.

# ⚙️ Implementation
- [ ] Create an `Object` to represent the application state, and make the characters a property.
- [ ] Add a property to the application state to track the index of the `currentCharacter`.
- [ ] Define a CSS class to highlight the `current-character`.
- [ ] Enhance function that renders a character to conditionally add a special `current-character` class.

![see-next-letter](https://user-images.githubusercontent.com/39274811/40800051-1fe3d208-64c4-11e8-8fbe-97c8dcabc7cf.png)

**Comment by franzsalvador** [comment]
Submission approved. Closing issue.
